# CMA Predefined Excel Row Map
# This maps each Excel row in the master sheet to the corresponding extraction field and logic.

CMA_ROW_MAP = {
    # ── Operating Details ──
    12: {"section": "operating_details", "field": "Operating months", "type": "number", "default": 12},

    # ── P&L / Operating Statement ──
    14: {"section": "sales", "field": "Domestic Sale", "type": "number"},
    15: {"section": "sales", "field": "Export Sale", "type": "number"},
    21: {"section": "cost_of_sales", "field": "Freight & Handling Expenses", "type": "number"},
    22: {"section": "cost_of_sales", "field": "Vehicle Running Expenses", "type": "number"},
    23: {"section": "cost_of_sales", "field": "Stores & Spares (Imported)", "type": "number"},
    24: {"section": "cost_of_sales", "field": "Stores & Spares (Indigenous)", "type": "number"},
    25: {"section": "cost_of_sales", "field": "Fuel Expenses", "type": "number"},
    26: {"section": "cost_of_sales", "field": "Direct Labour", "type": "number"},
    27: {"section": "cost_of_sales", "field": "Repair & Maintenance", "type": "number"},
    28: {"section": "cost_of_sales", "field": "Other Manufacturing Expenses", "type": "number"},
    29: {"section": "cost_of_sales", "field": "Depreciation", "type": "number"},
    32: {"section": "cost_of_sales", "field": "Insurance", "type": "number"},
    33: {"section": "cost_of_sales", "field": "Transport Expenses", "type": "number"},
    46: {"section": "profitability", "field": "Selling Expenses", "type": "number"},
    47: {"section": "profitability", "field": "Administrative Expenses", "type": "number"},
    56: {"section": "other_income_expenses", "field": "Interest/Dividend/Royalties", "type": "number"},
    58: {"section": "other_income_expenses", "field": "Other Income", "type": "number"},
    70: {"section": "pnl", "field": "Provision for Taxes", "type": "number"},
    84: {"section": "interest", "field": "Interest on CC", "type": "number"},
    85: {"section": "interest", "field": "Interest on TL", "type": "number"},
    86: {"section": "interest", "field": "Other interests", "type": "number"},

    # ── Liabilities ──
    102: {"section": "current_liabilities", "field": "Short Term loans from Applicant Bank", "type": "number"},
    103: {"section": "current_liabilities", "field": "Short Term loans From Other banks", "type": "number"},
    107: {"section": "current_liabilities", "field": "Short Term Borrowings from Others", "type": "number"},
    108: {"section": "current_liabilities", "field": "Sundry Creditors (Trade)", "type": "number"},
    109: {"section": "current_liabilities", "field": "Advance Payment from Customers", "type": "number"},
    110: {"section": "current_liabilities", "field": "Net Provision for Taxation", "type": "number"},
    111: {"section": "current_liabilities", "field": "Dividend Payable", "type": "number"},
    112: {"section": "current_liabilities", "field": "Other Statutory Liabilities", "type": "number"},
    113: {"section": "current_liabilities", "field": "Overdue Term Liabilities", "type": "number"},
    114: {"section": "current_liabilities", "field": "Installments of term Loan", "type": "number"},
    116: {"section": "current_liabilities", "field": "Creditors for Capital expenses", "type": "number"},
    117: {"section": "current_liabilities", "field": "Other current Liabilities", "type": "number"},
    118: {"section": "current_liabilities", "field": "Provision for Others", "type": "number"},
    125: {"section": "term_liabilities", "field": "Term Loan from Bank", "type": "number"},
    126: {"section": "term_liabilities", "field": "Term Loan from Other Banks/Institutions", "type": "number"},
    127: {"section": "term_liabilities", "field": "Deferred Payments Credits", "type": "number"},
    128: {"section": "term_liabilities", "field": "Term deposits", "type": "number"},
    130: {"section": "term_liabilities", "field": "Unsecured Loans from Directors", "type": "number"},
    131: {"section": "term_liabilities", "field": "Security Deposits", "type": "number"},
    132: {"section": "term_liabilities", "field": "Unsecured Loans", "type": "number"},
    133: {"section": "term_liabilities", "field": "Long Term provisions", "type": "number"},
    137: {"section": "net_worth", "field": "Capital", "type": "number"},
    144: {"section": "net_worth", "field": "Share Premium", "type": "number"},

    # ── Assets ──
    158: {"section": "current_assets", "field": "Cash & Bank Balances", "type": "number"},
    159: {"section": "current_assets", "field": "Government securities", "type": "number"},
    160: {"section": "current_assets", "field": "Fixed Deposits with Banks", "type": "number"},
    161: {"section": "current_assets", "field": "Domestic Receivables", "type": "number"},
    162: {"section": "current_assets", "field": "Unbilled receivables", "type": "number"},
    163: {"section": "current_assets", "field": "Export Receivables", "type": "number"},
    164: {"section": "current_assets", "field": "Deferred receivables", "type": "number"},
    165: {"section": "current_assets", "field": "Refund Dues from Government Authorities", "type": "number"},
    172: {"section": "current_assets", "field": "Advances to Suppliers", "type": "number"},
    173: {"section": "current_assets", "field": "Net Advance Payment of Taxes", "type": "number"},
    176: {"section": "current_assets", "field": "Prepaid expenses", "type": "number"},
    177: {"section": "current_assets", "field": "Deposits-EMD & Fixed Deposits", "type": "number"},
    178: {"section": "current_assets", "field": "Other Current Assets", "type": "number"},
    182: {"section": "fixed_assets", "field": "Gross Block", "type": "formula", "formula": "=I182+I183"},
    183: {"section": "fixed_assets", "field": "Capital expenditure in work-in-process", "type": "number"},
    184: {"section": "fixed_assets", "field": "Depreciation to Date", "type": "formula", "formula": "=I184+J29-65.64"},
    187: {"section": "fixed_assets", "field": "Investments in Subsidiaries", "type": "number"},
    188: {"section": "fixed_assets", "field": "Investment in Others", "type": "number"},
    189: {"section": "fixed_assets", "field": "Advance to suppliers of Capital goods & Contractors", "type": "number"},
    190: {"section": "fixed_assets", "field": "Deferred Receivables", "type": "number"},
    191: {"section": "fixed_assets", "field": "Security Deposits", "type": "number"},
    194: {"section": "fixed_assets", "field": "Deferred Tax Asset", "type": "number"},
    195: {"section": "fixed_assets", "field": "Advance Tax/TDS", "type": "number"},
    196: {"section": "fixed_assets", "field": "Fixed Deposits", "type": "number"},
}

# Depreciation opening values row mapping (Row number in DEPRECIATION sheet)
DEPRECIATION_ROW_MAP = {
    4: {"asset": "Land", "has_dep": False},
    5: {"asset": "Office Premises", "has_dep": True},
    6: {"asset": "Furniture & Fixtures", "has_dep": True},
    7: {"asset": "Container", "has_dep": True},
    8: {"asset": "Office Equipment", "has_dep": True},
    9: {"asset": "Vehicles", "has_dep": True},
    10: {"asset": "Computer", "has_dep": True},
    12: {"asset": "Software", "has_dep": True},
}
